### ISSUE TITLE
Android app: when pay/receive amount input prompt is selected, entire screen truncated by another menu

### ISSUE THREAD

**Issue by vandonsel** [pitonite/exch_cx#4] opened 2024-07-27 01:38 UTC
When using the app and inputting the amount of coin to send or receive, the "exchange, orders, and history" menu appears and covers up current user input.

Steps
1. Launch app
2. Select number prompt by "You Pay" or "You Receive"

Result: Menu appears covering up screen including input prompts
Expected result: I imagine you want people to see what they're typing when they're inputting their amounts

App version 1.3.2
Phone: Samsung Galaxy S9 
Android Version: 10

![signal-2024-07-26-182952_002](https://github.com/user-attachments/assets/f0ea7ad8-e06b-49c8-83de-f40d2b7d3444)
![signal-2024-07-26-182959_002](https://github.com/user-attachments/assets/80a7ccc4-3bad-4289-8380-cbd4cd59a149)

**Comment by pitonite** [comment] 2024-07-27 01:42
Hi
that is not intended for sure, it's a bug
I'll check if I can reproduce in emulator

**Comment by vandonsel** [comment] 2024-07-27 01:52
Cannot reproduce on a TCL Ion X with Android 12

**Comment by pitonite** [comment] 2024-07-27 02:54
I can reproduce it on android emulator (android 10)
I'll try to fix it

**Comment by pitonite** [comment] 2024-07-27 06:40
Fixed in [v1.3.3](https://github.com/pitonite/exch_cx/releases/tag/v1.3.3)

**Closed as completed by pitonite** 2024-07-27 06:40 UTC
